name: Krzysztof Goliński
description: Adventures in code and art
author: Krzysztof Goliński
author_email: krzysztof@golinski.org
category_dir: /
baseurl: 
timezone: Europe/Warsaw
url: http://blog.golinski.org
permalink: /posts/:title
paginate: 5
paginate_path: ":num"
exclude: [README.md, Gemfile, Gemfile.lock, style.scss, CNAME]