name: Blog
description: Adventures in code and art
author: Krzysztof Goliński
author_email: krzysztof@golinski.org
category_dir: /
baseurl: 
timezone: Europe/Warsaw
url: http://blog.golinski.org
permalink: /posts/:title
exclude: [README.md, Gemfile, Gemfile.lock, style.scss, CNAME]
paginate: 5