name: Krzysztof Goliński
description: Adventures in code and art
author: Krzysztof Goliński
author_email: krzysztof@golinski.org
category_dir: /
excerpt_separator: <!--more-->
timezone: Europe/Warsaw
url: http://blog.golinski.org
permalink: /post/:title
plugins: [jekyll-paginate]
paginate: 5
paginate_path: ":num"
exclude: [README.md, Gemfile, Gemfile.lock, style.scss, CNAME]